### ISSUE TITLE
right channel is muted :(

### ISSUE THREAD

**Issue by karikera** [audioboy77/OpenMP3#4]
[kirby.zip](https://github.com/audioboy77/OpenMP3/files/2065780/kirby.zip)
I played this sound 
but right channel is muted at first part

I copied OpenMP result to sound buffer like this
```c
// readed - Buffer from OpenMP3
// nsample - from OpenMP3
// dest - Stereo sound buffer pointer
float * src1 = readed[0];
float * src2 = readed[1];
float src1_end = src1 + nsamples;
while (src1 != src1_end)
{
	*dest++ = (short)((*src1++) * SHRT_MAX);
	*dest++ = (short)((*src2++) * SHRT_MAX);
}
```

When i debug that, second channel is zero filled
![image](https://user-images.githubusercontent.com/6016498/40884696-afc709c6-6753-11e8-8f60-e637eeff5280.png)

Thanks for simple MP3 library!

**Comment by lieff** [comment]
Probably it's because actual data starts from 12523 byte. Correct ID3 skipping may help (or ID3 tag may be invalid).

**Comment by lieff** [comment]
I've checked other decoder, and it seems file handled correctly, ID3 skipped, stereo present:
![image](https://user-images.githubusercontent.com/10080078/40885728-a24007c2-6734-11e8-866d-a640166081d6.png)

**Comment by karikera** [comment]
https://github.com/audioboy77/OpenMP3/pull/5
sound is corrected when i changed it!

**Comment by audioboy77** [comment]
can you submit the file, i will take a look

**Comment by karikera** [comment]
I uploaded sound file in first comment!
