### ISSUE TITLE
How seek time position ?

### ISSUE THREAD

**Issue by dmxvlx** [audioboy77/OpenMP3#6]
Hi guys !

Please tip me: how can I set needed time position for frame/iterator ?
Any help, please .

Thanks

**Comment by dmxvlx** [comment]
Ok. For get samples without decoding frame (for fast time),
we can add into class Frame method `UInt GetSamples() const;'
(include/openmp3.h), and then implementation will be (src/iterator.cpp):

[CODE]
OpenMP3::UInt OpenMP3::Frame::GetSamples() const
{
  return m_length;
}
[/CODE]


For now we can do iterate to needed time:
[CODE]
float to = 30.0f; // needed time pos 30 seconds
float pos = 0.0f; // cursor time position

/// \note please note: you need recreate iterator with beginning state
// then after found position you can replace old iterator with result iterator
while (itr.GetNext(frame)) {
  pos += float(frame.GetSamples())*(1.0f/frame.GetSampleRate());
  if (pos >= to) {
    // ok, we have needed position
    break;
  }
}

--
Enjoy :)
[/CODE]

**Comment by audioboy77** [comment]
Usage question rather than issue (and your own answer is correct), so closing this
