### ISSUE TITLE
how can I get decoding frame size for 441 samples ?

### ISSUE THREAD

**Issue by dmxvlx** [audioboy77/OpenMP3#7]
Hi audioboy77 !

Can you explain me: how to get decoding samples into frame size 441 ?

I have audio output device, opened with 441 frame size (samples per channel) - 10 millisecons.
When I'm trying to split 1152 samples which I got by OpenMP3::Iterator::GetNext()
into pieces by 441, I'm getting distortion on the sounds data.

--
thanks

**Comment by lieff** [comment]
You must buffer 1152 samples and fill audio device, sample pseudo-code:
```
int samples_to_fill = 441;
do {
    if (!samples_in_buffer)
        decode_new_1152_samples_in_buf();
    int samples_to_copy = MIN(samples_in_buffer, samples_to_fill);
    int bytes_to_copy = samples_to_copy*2*channels;
    memcpy(audio_dev_buf, decoder_buf, bytes_to_copy);
    audio_dev_buf += bytes_to_copy;
    decoder_buf += bytes_to_copy;
    samples_to_fill -= samples_to_copy;
} while (samples_to_fill && !decoder_end)
if (samples_to_fill)
    memset(audio_dev_buf, 0, samples_to_fill*2*channels);
```

**Comment by dmxvlx** [comment]
@lieff thanks a lot !
sorry for my delayed viewing and answering ...
