### ISSUE TITLE
Add method to decode via byte[]

### ISSUE THREAD

**Issue by DirtyNative** [audioboy77/OpenMP3#8]
Because UWP districts loading files from different locations than the .exe, there should be a method that takes the byte[] of a file (already loaded at other position in program) and then decodes it. Similar to:
public Mp3Decoder(string mp3File)
        { .... }

but with:
public Mp3Decoder(byte[] mp3Bytes)
        { ... }

**Comment by audioboy77** [comment]
you seem to be confused, that is already the case...  there is no file handling inside OpenMP3
